---
- name: Test libvirt role
  hosts: localhost
  become: yes
  vars:
    ansible_user: lab-user
    ansible_ssh_private_key_file: /home/lab-user/.ssh/cluster-key
    ansible_connection: ssh
    ansible_host: 127.0.0.1
  roles:
    - role: "{{ playbook_dir }}"
      vars:
        libvirt_user: "{{ ansible_user }}"
