---
# tasks for libvirt role

- name: Install required packages
  ansible.builtin.dnf:
    name:
      - libvirt
      - libvirt-client
      - qemu-kvm
      - virt-manager
      - virt-install
      - python3-libvirt
    state: present

- name: Enable and start libvirtd service
  ansible.builtin.systemd:
    name: libvirtd
    state: started
    enabled: true

- name: Add user to libvirt group
  ansible.builtin.user:
    name: "{{ libvirt_user }}"
    groups: libvirt
    append: true
  when: libvirt_user is defined

- name: Set libvirtd unix_sock_group
  ansible.builtin.lineinfile:
    path: /etc/libvirt/libvirtd.conf
    regexp: '^#?\s*unix_sock_group\s*='
    line: 'unix_sock_group = "libvirt"'
    state: present

- name: Set libvirtd unix_sock_rw_perms
  ansible.builtin.lineinfile:
    path: /etc/libvirt/libvirtd.conf
    regexp: '^#?\s*unix_sock_rw_perms\s*='
    line: 'unix_sock_rw_perms = "0770"'
    state: present

- name: Restart libvirtd service
  ansible.builtin.systemd:
    name: libvirtd
    state: restarted
