---
- name: Converge
  hosts: all
  become: true
  vars:
    libvirt_user: "ansible"

  collections:
    - community.libvirt

  tasks:
    - name: Include ansible-role-libvirt
      ansible.builtin.include_role:
        name: ansible-role-libvirt
