---
- name: Converge
  hosts: all
  become: true
  vars:
    libvirt_user: "ansible"

  pre_tasks:
    - name: Install community.libvirt collection
      ansible.builtin.command: ansible-galaxy collection install community.libvirt
      delegate_to: localhost
      run_once: true
      changed_when: false

  tasks:
    - name: Include libvirt role
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
