---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Check if libvirtd service is running
      ansible.builtin.systemd:
        name: libvirtd
      register: libvirtd_status
      failed_when: not libvirtd_status.status.ActiveState == "active"

    - name: Verify libvirt packages are installed
      ansible.builtin.dnf:
        name:
          - libvirt
          - libvirt-client
          - qemu-kvm
          - virt-manager
          - virt-install
          - python3-libvirt
        state: present
      check_mode: true
      register: pkg_status
      failed_when: pkg_status.changed

    - name: Check libvirt socket permissions
      ansible.builtin.stat:
        path: /var/run/libvirt/libvirt-sock
      register: socket_status
      failed_when: not socket_status.stat.mode == "0770"

    - name: Get libvirt host capabilities
      community.libvirt.virt:
        command: capabilities
      register: libvirt_caps
      failed_when: libvirt_caps.failed

    - name: Display libvirt capabilities
      ansible.builtin.debug:
        var: libvirt_caps

    - name: List all domains
      community.libvirt.virt:
        command: list_vms
      register: domain_list
      failed_when: domain_list.failed

    - name: Display domain list
      ansible.builtin.debug:
        var: domain_list

    - name: Get libvirt host info
      community.libvirt.virt:
        command: nodeinfo
      register: node_info
      failed_when: node_info.failed

    - name: Display node info
      ansible.builtin.debug:
        var: node_info

    - name: Check libvirt connection URI
      ansible.builtin.command: virsh uri
      register: virsh_uri
      changed_when: false
      failed_when: virsh_uri.rc != 0

    - name: Display URI
      ansible.builtin.debug:
        var: virsh_uri.stdout
